- README.md
- databases/README.md
- databases/extract_transactions_for_test.sql
We were recently asked by QA & Test to extract data on transactions so they could replicate real world tests of large billing runs. We also now have an understanding of how to connect to our databases in the non-production environments.
So this change creates a place to store that information and as the first item adds the script we used to extract the transaction data (connecting to the databases will come later!)
> Add new database folder test query to project

- openapi/openapi.yml
- openapi/versions/swagger_v0-3-0.yml
We forgot to update the description about large bill runs causing an error in the API when we merged #18 . v0.3.0 of the API actually includes a fix for the issue.
But rather than removing it, this change updates it to reflect what we do know; large bill runs can take 3 hours or more to generate a summary.
> Update API issue about large bill run errors

- openapi/paths/v1/billruns/bill_run_send.yml
See [Create a PATCH version of billrun send endpoint](https://github.com/DEFRA/charging-module-api/pull/156)
The convention in the API is for any endpoint which is used to tell us to do something, for example, 'approve' a bill run, to expect a `PATCH` request. That is apart from 'send' a bill run. That's a `POST`.
Like nails on a blackboard, it causes us pain whenever we see it!
As agreed with the WRLS team we have added a new `PATCH` version of the endpoint to the API which works _exactly_ the same as the existing endpoint. After we've shipped the next version of the API we'll remove the `POST` version.
Doing it this way means we won't break their existing system and allow them time to migrate to using the new `PATCH` version.
This change updates the Open API spec to include the new …
> Add PATCH version of bill run /send endpoint

- openapi/openapi.yml
- openapi/paths/v1/calculate_charge/deprecated_calculate_charge.yml
- openapi/paths/v1/customer_changes/deprecated_customer_changes.yml
See [Underscores in URLs? Oh my!](https://github.com/DEFRA/charging-module-api/pull/164)
Most likely it was because that's what the underlying controller/endpoints are called, we seem to have some endpoints that expect an underscore in the path.
It's perfectly permissible. However, it's definitely not the convention for URLs. To quote Google
> Consider using punctuation in your URLs. The URL **http://www.example.com/green-dress.html** is much more useful to us than **http://www.example.com/greendress.html**. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.
So before the API hits a live production environment, we're taking the opportunity to update it to follow the current convention of using dashes.
There is also the 'blackboard' effect on us as a delivery …
> Underscores in urls? Oh my!

- postman/README.md
When the guide was first written we were just intending to maintain a single version of the spec for publishing to [SwaggerHub](https://swagger.io/tools/swaggerhub/). Since then we have moved to generating and retaining a version of the spec for each release of the CHA.
So this change updates to the guide to take account of this.
> Fix Postman documentation after changes in OpenAPI

- openapi/schema/fields.yml
- openapi/schema/parameters.yml
- openapi/schema/schemas.yml
- openapi/version_2/openapi.yml
- openapi/version_2/paths/admin/authorised_system.yml
- openapi/version_2/paths/admin/authorised_systems.yml
- openapi/version_2/paths/admin/health/airbrake.yml
- openapi/version_2/paths/admin/health/database.yml
- openapi/version_2/paths/admin/regime.yml
- openapi/version_2/paths/admin/regimes.yml
- openapi/version_2/paths/v2/billruns/bill_runs.yml
- openapi/version_2/paths/v2/billruns/transactions/bill_run_transactions.yml
- openapi/version_2/paths/v2/calculate_charge/calculate_charge.yml
- openapi/versions/draft_v2.yml
This update covers updating the spec to include those endpoints that are actually available for use in V2 of the API.
> Update OpenAPI version 2 draft spec with available

- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/bill_run_generate.yml
One of the key changes in Version 2 is that we are breaking up the functionality covered in the Version 1 view bill run endpoint.
At this time V1
- will generate the summary if one does not exist
- return a holding response until the summary is generated
- return a view of the bill run that includes _all_ transactions
On that last point we have bill runs with more than 9,000 transactions. When you add all the invoice summary information the response becomes massive!
So the first part of breaking it up is to create a dedicated `generate-summary` endpoint.
We not actually built it yet. But for this endpoint its not a case of if, but when. So we are adding it now to the open api spec to aid with discussion about it.
> Add generate bill run summary endpoint

- openapi/schema/schemas.yml
- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/versions/draft_v2.yml
One of the key changes in Version 2 is that we are breaking up the functionality covered in the Version 1 view bill run endpoint.
At this time V1
- will generate the summary if one does not exist
- return a holding response until the summary is generated
- return a view of the bill run that includes _all_ transactions
On that last point, we have bill runs with more than 9,000 transactions. When you add all the invoice summary information the response becomes massive!
We've already updated the Version 2 spec with the proposed 'generate summary' endpoint. This change adds details on view bill run, and how we intend to change it from version 1.
We will now just return what bill run and invoice information we hold in the database; no holding response and no hiding the data if the summary is …
> Add view bill run endpoint

- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/bill_run_send.yml
- openapi/versions/draft_v2.yml
We've not yet implemented this endpoint in Version 2. But we do intend to make some changes when we do. So to facilitate the final design and implementation this change adds the endpoint with the proposed changes.
For reference, those changes are
- It will not longer generate the summary if this has not been done. Instead it will reject the request
- It will just return the file name the bill run will be assigned to instead of the full bill run summary
> Add bill run send endpoint

- openapi/schema/fields.yml
- openapi/schema/parameters.yml
- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/invoices/invoice.yml
- openapi/version_2/paths/v2/licences/licence.yml
As part of Version 2 of the API invoices and licences will be actual records in the DB with links to the relevant bill runs and transactions. This is all part of the changes we are making to fix the performance issues in the API.
Because of this it means we can add endpoint dedicated to there deletion that work based on ID rather than as a query param. The benefit to us is
- We can build the endpoint to be specific to the task, for example, deleting an invoice and all the work needed to update the bill run and its summary details
- We can be better assured we are deleting the right thing as the client system has provided the IDof the record, rather than just a reference
Exactly where these endpoints will sit is still unknown. For example, should they also sit under `../bill-runs/` or …
> Add invoice and licence delete endpoints to spec

- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/bill_run_status.yml
- openapi/versions/draft_v2.yml
The workflow around bill runs is
- create bill run
- add transactions
- generate summary
- keep checking bill run status until summary is complete
- get bill run view
At the moment the only endpoint to check the status of the bill run is the view bill run. We are intending to remove the transaction detail to make it more performant. But we'll still have to collate all invoice and licence detail to provide a full response.
This seems overkill and will impact performance if all a client system actually needs to know is if the status has gone from `generating` to `summarised`. So this change adds details of a new endpoint it is likely we'll add to V2 that can be used to just check the status of a bill run.
> Add bill run status endpoint to v2 spec

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/invoices/invoice.yml
- openapi/versions/draft_v2.yml
Thoughat this time we are not trying to define the final view bill run response (we've not built it yet!) we also know that the conversation could be diverted if people construe it in that way. So this change adds some properties to the view bill run response that exist in V1, and which we fully expect to include in V2, but which we haven't added to our examples in the spec.
> Add missing properties to v2 bill run response

- openapi/version_2/openapi.yml
- openapi/versions/draft_v2.yml
Spotted during a call that the V2 paths for bill runs has an inconsistent mix of V1 and V2 versions.
> Fix paths in API spec v2 bill runs

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/versions/draft_v2.yml
`transactionFileReference` is something that gets populated when the `/send` request is made. But as part of our intent to keep the structure the same for the view bill run it will make things clearer if we include it in our examples, even though it will be empty.
So this updates the Version 2 spec to include it in the examples.
> Add transaction file ref to View bill run response

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/versions/draft_v2.yml
This change updates the examples for the v2 view bill run endpoint to reflect the current output.
> Updated v2 view bill run examples

- .gitignore
- README.md
- dockerhub/README.md
- dockerhub/version_1/.env.example
- dockerhub/version_1/README.md
- dockerhub/version_1/docker-compose.yml
- dockerhub/version_1/makefile
- dockerhub/version_2/.env.example
- dockerhub/version_2/README.md
- dockerhub/version_2/docker-compose.yml
- dockerhub/version_2/makefile
https://trello.com/c/jHORNdnQ
We have now made [version 2](https://github.com/defra/sroc-charging-module-api) available as a docker image in [Docker Hub](https://hub.docker.com/r/environmentagency/sroc-charging-module-api). As part of that, we have produced a guide on how to get started, along with an example `docker-compose.yml` and `makefile`.
Normally, this information would all be added to the README on docker hub. But we have also enabled automated builds. This means you can always grab whatever is on `main` as a docker image plus whenever we add a tag docker hub automatically builds a matching image. Sweet!
The downside is the standard behaviour of an automated build is to [overwrite the README in docker hub with the one from the source …
> Add notes about docker hub integration

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/billruns/bill_run_status.yml
- openapi/versions/draft_v2.yml
Whilst working on the latest changes we spotted one inconsistency with the current examples and what we actually return (it's `zeroLineCount` in the invoice details, not `zeroValueLineCount`).
Also, [Develop Approve Bill Run (v2)](https://trello.com/c/SmiI8YaG) is going to make some changes to the bill run structure which will affect the examples. We'll just use `status:` to show a bill run is 'approved', no need for a separate field and makes things less complex in the code.
So, we cover that change here as well and add a new example to help demonstrate it.
> Correct V2 view bill run API examples

- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
We are just on the cusp of making the view bill run invoice endpoint available. What we had as the example before was just a placeholder. We now have a working version so can update the spec to use what it currently returns.
We can still expect some feedback and changes once WRLS have had a chance to review it. But it at least represents the first version they will see.
> Update view bill run invoice API spec example

- openapi/version_2/paths/v2/billruns/bill_run_approve.yml
The bill run `/approve` endpoint is now complete and will be available in the next Docker release (already in `latest`).
> Update approve endpoint API V2 documentation

- openapi/version_2/openapi.yml
- openapi/version_2/paths/admin/test/bill_runs.yml
- openapi/versions/draft_v2.yml
We recently added a new endpoint to the `/admin` path to support being able to generate large bill runs quickly. The intent is to support working with and testing other endpoints to see how they behave with realistic volumes.
Depending on the request sent we can ask the endpoint to create a bill run with a mix of invoice types. This change covers full details about the endpoint, including what the invoice types are, the ratio of invoices to transactions (1 to 3), and how to use it.
> Add test bill run generator API details

- openapi/version_2/openapi.yml
- openapi/version_2/paths/admin/test/transaction.yml
- openapi/versions/draft_v2.yml
We have recently added a 'test' specific view transaction endpoint. Like our view regime and authorised system endpoints we apply no logic to the formatting of the response from the DB. The data is returned as is.
It also includes all data held in the related bill run, invoice and licence records. The intent is to give easy access to everything related to a transaction to support testing. As we make changes to the DB record details the endpoint will continue to 'just' work.
> Add test view transaction endpoint API details

- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
We've just created v0.4.0 of [version 2](https://github.com/defra/sroc-charging-module-api) of the API which makes a number of new endpoints available
- Delete an invoice from a bill run
- View a bill run invoice
This updates the V2 open API spec to match the change in status.
> Update V2 Open API spec to match v0.4.0 changes

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/versions/draft_v2.yml
Just spotted that the `DELETE /bill-runs` endpoint is not listed in the V2 open API spec.
This change adds it!
> Add missing DELETE bill run to V2 Open API spec

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/versions/draft_v2.yml
https://trello.com/c/IKn83UpO/1927-s-develop-delete-bill-run-v2
This change updates the draft v2 Swagger docs to include the `DELETE /v2/{regime}/bill-runs/{billRunId}` endpoint.
> Update v2 docs with DELETE bill-runs endpoint

- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/bill_run_send.yml
The `PATCH /v2/{regimeId}/bill-runs/{billRunId}/send` endpoint is now available. This updates the Open API spec to match what is currently implemented and set the status to 'available'.
> Update Open API spec for V2 /send endpoint

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/billruns/bill_run_status.yml
- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
This update is just some housekeeping and updates to the V2 open API spec based on fixes and changes we have made recently.
- update view bill run examples to remove line count/value fields
- update view bill run examples to include invoice transaction reference
- add view bill run examples for `sent` and `billed`
- update view invoice response to remove line count/value fields
- add all remaining status examples to status endpoint
> Update V2 Open API spec with latest changes

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
With the release of SROC CMA V2 v0.6.2 this change is some minor updates to the examples to bring them in line with what the API is now doing.
> Update CMA V2 Open API spec with latest changes

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/billruns/bill_run_approve.yml
- openapi/version_2/paths/v2/billruns/bill_run_generate.yml
- openapi/version_2/paths/v2/billruns/bill_run_status.yml
- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/version_2/paths/v2/billruns/transactions/bill_run_transactions.yml
- openapi/versions/draft_v2.yml
There are no real changes to any of the API end points. We have added some more examples to cover when a bill run has been determined as `billing_not_required`.
The key changes are moving some of the endpoints to the status of `tested` to reflect the work @anwarisse1 has been doing.
> Update V2 Open API spec to latest

- openapi/version_2/paths/v2/billruns/transactions/bill_run_transactions.yml
- openapi/versions/draft_v2.yml
A recent defect report from WRLS team highlighted that they maybe didn't realise that v2 has shifted from using `newLicence` to `subjectToMinimumCharge`. This change amends the example request for `AddBillRunTransaction` to include this.
> Add subjectToMinimumCharge to Swagger docs

- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
We have amended the API to return a boolean for this field instead of a string.
> Update compensationCharge in OpenAPI /invoices

- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
As per [Remove transaction level status](https://github.com/DEFRA/sroc-charging-module-api/pull/340) the status property has been removed from bill run transactions.
This change updates the V2 Open API spec to match.
> Remove transaction status from OpenAPI V2 spec

- openapi/version_2/openapi.yml
- openapi/version_2/paths/admin/customers.yml
- openapi/version_2/paths/admin/test/customer.yml
- openapi/version_2/paths/admin/test/customers.yml
- openapi/version_2/paths/v2/billruns/transactions/bill_run_transactions.yml
- openapi/version_2/paths/v2/customer_changes/customer_changes.yml
- openapi/versions/draft_v2.yml
This covers
- addition of new `/admin` and `/test` customer endpoints
- correction to the `POST /customer-changes` response code from 204 to 201
- adding example of `409 conflict` response to the `POST /transactions` endpoint
> Update CHA V2 swagger API with latest changes

- openapi/schema/parameters.yml
- openapi/version_2/openapi.yml
- openapi/version_2/paths/v2/billruns/invoices/invoice_rebill.yml
- openapi/versions/draft_v2.yml
Add details for the new bill run invoice rebilling endpoint to the V2 OpenAPI spec. At this time there is currently an endpoint available, but it's not doing all the checks outlined here or returning the response we've documented. This is why it is recorded as being 'suggested'. We'll bump it to available just as soon as we have hooked the endpoint up to the new services.
> Add invoice rebill endpoint to V2 OpenAPI spec

- openapi/version_2/paths/v2/billruns/bill_run.yml
- openapi/version_2/paths/v2/billruns/invoices/invoice.yml
- openapi/versions/draft_v2.yml
[Recent](https://github.com/DEFRA/sroc-charging-module-api/pull/421) [changes](https://github.com/DEFRA/sroc-charging-module-api/pull/422) have added rebilling fields to the output of the View Bill Run and View Bill Run Invoice endpoints. This change updates the docs to reflect these changes.
> Add rebilling fields to View Bill Run and Bill Run Invoice docs

- openapi/README.md
Implementing [Update V2 OpenAPI spec ready for API release](https://github.com/DEFRA/sroc-service-team/pull/69) was a major restructuring of the project regards our OpenAPI specs. In essence, we now only maintain one.
However, we still have README's that refer to the maintenance of both specs. This change rectifies them to make things clear we now only maintain the one.
> Update OpenAPI README's

- openapi/openapi.yml
- openapi/versions/draft.yml
We have descriptions and schemas for each of the endpoints but the OpenAPI spec doesn't provide any info on how they are supposed to hang together.
This change adds an initial attempt at describing the workflows we expect client systems to follow and how they overlap with the Charging Module.
> Add initial info on Workflows to CHA OpenAPI spec

- openapi/openapi.yml
- openapi/versions/draft.yml
The Charging Module often makes reference to things like 'deminimis' and 'minimum charge' but we don't actually provide any explanations of what they are.
As a first step, this change adds some initial explanations we can correct/build-on if needed.
> Add initial rule explanations to OpenAPI spec

- openapi/README.md
- openapi/openapi.yml
- openapi/paths/admin/bill_runs.yml
- openapi/versions/draft.yml
After [creating the admin 'send bill run' endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/429), we add it to the Swagger docs.
> Add admin send bill run endpoint to docs

- openapi/paths/v2/customer_changes/customer_changes.yml
We currently make reference to a customer file that the CM generates and sends to SSCL SOP. However, we don't actually provide any details about it.
This change adds a bit more info plus an example of the file to the OpenAPI spec.
> Add details about the customer file to API spec

- openapi/paths/v2/customer_changes/customer_changes.yml
- openapi/versions/draft.yml
In [Add details about the customer file to API spec](https://github.com/DEFRA/sroc-service-team/pull/77) we added details on the customer file we generate and send to SSCL SOP to the Open API spec.
But immediately after we spotted some errors with the example data used. This change corrects those errors.
> Fix Open API spec customer file details

- openapi/paths/v2/bill_runs/bill_run_send.yml
- openapi/versions/draft.yml
We currently make reference to a transaction file that the CM generates and sends to SSCL SOP. However, we don't actually provide any details about it.
This change adds a bit more info plus an example of the file to the OpenAPI spec.
> Add details about the transaction file to API spec

- openapi/paths/admin/authorised_system.yml
- openapi/paths/admin/bill_runs.yml
- openapi/paths/admin/regime.yml
- openapi/paths/admin/test/customer.yml
- openapi/paths/admin/test/transaction.yml
- openapi/paths/v2/bill_runs/bill_run.yml
- openapi/paths/v2/bill_runs/bill_run_approve.yml
- openapi/paths/v2/bill_runs/bill_run_generate.yml
- openapi/paths/v2/bill_runs/bill_run_send.yml
- openapi/paths/v2/bill_runs/bill_run_status.yml
- openapi/paths/v2/bill_runs/bill_runs.yml
- openapi/paths/v2/bill_runs/invoices/invoice.yml
- openapi/paths/v2/bill_runs/invoices/invoice_rebill.yml
- openapi/paths/v2/bill_runs/licences/licence.yml
- openapi/paths/v2/bill_runs/transactions/bill_run_transactions.yml
- openapi/paths/v2/calculate_charge/calculate_charge.yml
- openapi/paths/v2/customer_changes/customer_changes.yml
- openapi/versions/draft.yml
We have some examples of the `4xx` responses the [SROC Charging Module API](https://github.com/DEFRA/sroc-charging-module-api) might return but it's not complete.
There are some shared responses, for example, when the bill run is unknown that are not included which we feel are needed to make the spec complete.
So, this change goes through the endpoints adding any missing `4xx` responses we are aware of.
> Add missing 4xx response to Open API spec

- openapi/paths/v2/bill_runs/bill_run_send.yml
- openapi/versions/draft.yml
After a review our awesome BA spotted a few errors with the transaction file information in the Open API documentation.
> Fix errors in Open API transaction file details

- README.md
- dockerhub/README.md
- openapi/openapi.yml
- openapi/versions/draft.yml
- releasing/cha.md
- releasing/tcm.md
- services/README.md
Having finally shipped the initial [Charging Module API](https://github.com/DEFRA/sroc-charging-module-api) which currently is only used by the WRLS team, we're thinking ahead to working with other services on things other than SROC.
With that in mind, we have officially (ish) renamed ourselves.
- the service we look after shall be henceforth known as **Charging Module** (made up of the TCM, CM, and Rules Service)
- we shall be henceforth known as the **Charging Module Team**
- we shall no longer use the prefix **SROC** on everything
This change just updates the root README and any other obvious references. In the future, we'll do the harder task of updating our repo names and anything we find that links to them.
> Team name change!

- openapi/openapi.yml
- openapi/paths/v2/bill_runs/bill_run.yml
- openapi/paths/v2/bill_runs/invoices/invoice.yml
- openapi/paths/v2/bill_runs/licences/licence.yml
- openapi/schema/fields.yml
- openapi/schema/schemas.yml
- openapi/versions/draft.yml
- openapi/versions/v0-12-0.yml
https://eaflood.atlassian.net/browse/CMEA-74
This updates the Open API spec for the CHA (Charge Module API) with the latest changes, including highlighting delete licence as available. It then also generates a corresponding version for v0.12.0.
> Update Open API spec with latest & generate ver.

- openapi/versions/v0-13-0.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for v0.13.0 of the API.
> Add Open API doc for v0.13.0 of CHA

- openapi/versions/v0-13-1.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for v0.13.1 of the API.
> Add Open API doc for v0.13.1 of CHA

- openapi/openapi.yml
- openapi/versions/draft.yml
We've just spotted that the test customer-file endpoints in the spec (`/admin/test/{regime}/customers` and `/admin/test/customers/{customerFileId}`) do not match what is actually in the API (`/admin/test/{regime}/customer-files` and `/admin/test/customer-files/{customerFileId}`). This change fixes it.
> Fix CHA OpenAPI spec test customer files endpoint

- openapi/versions/v0-13-2.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for v0.13.2 of the API.
> Add Open API doc for v0.13.2 of CHA

- openapi/versions/v0-13-3.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for `v0.13.3` of the API.
> Add Open API doc for v0.13.3 of CHA

- rfc/tcm.md
https://eaflood.atlassian.net/browse/CMEA-91
We added some guidance and an example for the CHA back in [Add section and guides for RfC's](https://github.com/DEFRA/sroc-service-team/pull/91). At the same time, we added some stub pages for the RfC and the rules service.
We're now ready to raise an actual RfC for the TCM. So, it seems a great time to also knock off adding a TCM example to these guides.
> Add TCM RfC example to docs

- openapi/paths/admin/test/customers.yml
- openapi/versions/draft.yml
We hadn't spotted that [Document list customer files endpoint](https://github.com/DEFRA/sroc-service-team/pull/102) had inadvertently duplicated the endpoint ID of the existing test endpoint.
This change fixes that and updates `draft.yml`.
**Note**
We have a number of alignment changes in `draft.yml` as well. This was because the JSON was converted to YAML using [yq](https://mikefarah.gitbook.io/yq/) instead of (https://www.json2yaml.com/) as the site was down at the time of making the change.
We don't mind. In fact, we think it does a better job! For reference yq was installed using `brew install yq` and the command to get yq to convert our json was `yq eval -P openapi/openapi.json > openapi/versions/draft.yml`.
> Fix Customer Files endpoint ID's

- openapi/schema/parameters.yml
- openapi/versions/draft.yml
In [Document list customer files endpoint](https://github.com/DEFRA/sroc-service-team/pull/102) we added details about our new customer file endpoint which includes an optional path parameter. Hapi is fine with this and in our opinion, it looks much cleaner. However, Swagger doesn't support optional path parameters
> In OpenAPI, a path parameter is defined using in: path. The parameter name must be the same as specified in the path. Also remember to add required: true, because path parameters are always required.
>
> https://swagger.io/docs/specification/describing-parameters/#path-parameters
So, `required: false` is an invalid attribute for a path param in Swagger and SwaggerHub highlights it as an error. The only workaround is to drop the required and document the fact it's optional ☹️
> Fix invalid value for customer files 'required'

- openapi/versions/v0-14-0.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for `v0.14.0` of the API.
> Add Open API doc for v0.14.0 of CHA

- openapi/versions/v0-14-1.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for `v0.14.1` of the API.
> Add Open API doc for v0.14.1 of CHA

- openapi/versions/v0-15-0.yml
We've already made sure the `draft.yml` is up to date. So, this just adds the generated version for `v0.15.0` of the API.
> Add Open API doc for v0.15.0 of CHA

- openapi/versions/v0-15-0.yml
When updating the docs for `v0.15.0` we inadvertently left the draft notice at the top of the file. This PR removes this.
> Remove draft notice from `v0-15-0.yml`
